In [2]:
# numpy allows us to use matrices and arrays
 
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print (a)
print (b)

[1 2 3]
[4 5 6]


In [5]:
type(a)

numpy.ndarray

In [6]:
#basic operation in array
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [8]:
#creating a 2d array
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
# creating a 3d array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# craeting an array with a specific data type
print(a.dtype)

int64


In [ ]:
# to get number of dimension of array
print(a.ndim)

2


In [ ]:
# to get number of rows and column in array
print(a.shape)

(2, 3)


In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [24]:
np.random.randint(10,30)

28

In [25]:
np.random.randint(10,30, size =(3,3)) 

array([[22, 19, 21],
       [25, 13, 23],
       [18, 29, 21]], dtype=int32)

In [27]:
x = np.array([[7,2,3],[2,3,4],[7,7,6]])
y = np.array([[5,6,2],[3,4,1],[3,4,6]])
print(x)
print(y)

[[7 2 3]
 [2 3 4]
 [7 7 6]]
[[5 6 2]
 [3 4 1]
 [3 4 6]]


In [ ]:
#1by1 multiplication
print(x*y)

[[35 12  6]
 [ 6 12  4]
 [21 28 36]]


In [ ]:
#matrix multiplication
print(x@y)

[[50 62 34]
 [31 40 31]
 [74 94 57]]


In [30]:
print(x.dot(y))

[[50 62 34]
 [31 40 31]
 [74 94 57]]


In [31]:
x.prod()

np.int64(296352)

In [32]:
x.mean()

np.float64(4.555555555555555)

In [33]:
#mean of each column
x.mean(axis = 0)


array([5.33333333, 4.        , 4.33333333])

In [ ]:
#mean of each row
x.mean(axis = 1)

array([4.        , 3.        , 6.66666667])

In [35]:
print(x.sum())
print(x.var())
print(x.std())

41
4.246913580246913
2.060804110110156


In [36]:
z = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(z,25))#25th percentile
print(np.percentile(z,50))#50th percentile
print(np.percentile(z,75))#75th percentile

3.0
5.0
7.0


In [37]:
arr = np.random.randint(10,50, size = (4,4))
print(arr)

[[40 46 17 25]
 [48 14 10 48]
 [22 11 13 42]
 [38 43 30 39]]


In [38]:
print('8x2')
print(arr.reshape(8,2))

8x2
[[40 46]
 [17 25]
 [48 14]
 [10 48]
 [22 11]
 [13 42]
 [38 43]
 [30 39]]


In [39]:
print(x[0]) #first row
print(x[1]) #second row

[7 2 3]
[2 3 4]


In [ ]:
print(x[0,0])#fisrt row first element

7


In [ ]:
print(x[0,1]) #first row second element

2
